export interface IMDStationProfile {
  stationId: string;
  name: string;
  hindiName: string;
  state: string;
  latitude: number;
  longitude: number;
  elevationM: number;
  rmcDivision: string;
  wmoBlockNo: string;
  sensorMetadata: {
    tempSensor: string;
    pressureSensor: string;
    humiditySensor: string;
    dataloggerModel: string;
    telemetryUplink: string;
    batteryVoltage: string;
    lastCalibDate: string;
    calibCertNo: string;
  };
  baseline: {
    tempMean: number;
    pressureMean: number;
    humidityMean: number;
  };
  status?: 'OPERATIONAL' | 'SCHEDULED_CALIBRATION';
}

export const IMD_AWS_STATIONS: IMDStationProfile[] = [
  {
    stationId: 'AWS-DEL-04',
    name: 'Safdarjung Observatory, New Delhi',
    hindiName: 'सफदरजंग वेधशाला, नई दिल्ली',
    state: 'Delhi (NCT)',
    latitude: 28.585,
    longitude: 77.206,
    elevationM: 216,
    rmcDivision: 'RMC New Delhi',
    wmoBlockNo: '42182',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A 4-Wire RTD (DIN EN 60751)',
      pressureSensor: 'Vaisala PTB110 Silicon Capacitive Barometer',
      humiditySensor: 'Vaisala Humicap 180R Thin-Film Polymer',
      dataloggerModel: 'Sutron 9210 XL DCP Logger',
      telemetryUplink: 'INSAT-3D UHF DCP (402.75 MHz) / BSNL VPN',
      batteryVoltage: '12.42 V (Float Nominal)',
      lastCalibDate: '14-Oct-2025',
      calibCertNo: 'CC-IMD-NABL-DEL-2025-0914',
    },
    baseline: { tempMean: 31.8, pressureMean: 1008.2, humidityMean: 58.0 },
  },
  {
    stationId: 'AWS-MUM-01',
    name: 'Colaba Observatory, Mumbai',
    hindiName: 'कुलाबा वेधशाला, मुंबई',
    state: 'Maharashtra',
    latitude: 18.900,
    longitude: 72.815,
    elevationM: 11,
    rmcDivision: 'RMC Mumbai',
    wmoBlockNo: '43057',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A 4-Wire RTD (DIN EN 60751)',
      pressureSensor: 'Vaisala PTB110 Silicon Capacitive Barometer',
      humiditySensor: 'Vaisala Humicap 180R Thin-Film Polymer',
      dataloggerModel: 'Campbell Scientific CR1000X',
      telemetryUplink: 'INSAT-3D UHF DCP (402.75 MHz) / MTNL 4G',
      batteryVoltage: '12.65 V (Float Nominal)',
      lastCalibDate: '02-Dec-2025',
      calibCertNo: 'CC-IMD-NABL-MUM-2025-1102',
    },
    baseline: { tempMean: 29.5, pressureMean: 1012.4, humidityMean: 78.0 },
  },
  {
    stationId: 'AWS-KOL-02',
    name: 'Alipore Meteorological Office, Kolkata',
    hindiName: 'अलीपुर मौसम कार्यालय, कोलकाता',
    state: 'West Bengal',
    latitude: 22.533,
    longitude: 88.333,
    elevationM: 6,
    rmcDivision: 'RMC Kolkata',
    wmoBlockNo: '42807',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A 4-Wire RTD (DIN EN 60751)',
      pressureSensor: 'Setra Model 278 Barometric Transducer',
      humiditySensor: 'Rotronic HygroClip2-S3',
      dataloggerModel: 'Sutron 9210 XL DCP Logger',
      telemetryUplink: 'INSAT-3D UHF DCP (402.75 MHz) / Jio Enterprise',
      batteryVoltage: '12.51 V (Float Nominal)',
      lastCalibDate: '22-Nov-2025',
      calibCertNo: 'CC-IMD-NABL-KOL-2025-0843',
    },
    baseline: { tempMean: 30.5, pressureMean: 1011.6, humidityMean: 82.0 },
  },
  {
    stationId: 'AWS-PUN-08',
    name: 'Shivajinagar Agricultural Observatory, Pune',
    hindiName: 'शिवाजीनगर कृषि वेधशाला, पुणे',
    state: 'Maharashtra',
    latitude: 18.531,
    longitude: 73.855,
    elevationM: 560,
    rmcDivision: 'RMC Mumbai',
    wmoBlockNo: '43063',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A 4-Wire RTD (DIN EN 60751)',
      pressureSensor: 'Vaisala PTB110 Silicon Capacitive Barometer',
      humiditySensor: 'Vaisala Humicap 180R Thin-Film Polymer',
      dataloggerModel: 'Astra Micro AWS-200',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL GPRS VPN',
      batteryVoltage: '12.38 V (Float Nominal)',
      lastCalibDate: '19-Jan-2026',
      calibCertNo: 'CC-IMD-NABL-PUN-2026-0041',
    },
    baseline: { tempMean: 28.2, pressureMean: 1010.5, humidityMean: 64.0 },
  },
  {
    stationId: 'AWS-CHN-03',
    name: 'Meenambakkam Observatory, Chennai',
    hindiName: 'मीनमबाक्कम वेधशाला, चेन्नई',
    state: 'Tamil Nadu',
    latitude: 12.994,
    longitude: 80.181,
    elevationM: 16,
    rmcDivision: 'RMC Chennai',
    wmoBlockNo: '43279',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A 4-Wire RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Vaisala Humicap 180R',
      dataloggerModel: 'Campbell CR1000X',
      telemetryUplink: 'INSAT-3D UHF DCP / Airtel IoT',
      batteryVoltage: '12.58 V (Float Nominal)',
      lastCalibDate: '09-Jan-2026',
      calibCertNo: 'CC-IMD-NABL-CHN-2026-0019',
    },
    baseline: { tempMean: 32.6, pressureMean: 1010.8, humidityMean: 74.0 },
  },
  {
    stationId: 'AWS-BLR-05',
    name: 'HAL Airport Meteorological Facility, Bengaluru',
    hindiName: 'एचएएल हवाई अड्डा मौसम सुविधा, बेंगलुरु',
    state: 'Karnataka',
    latitude: 12.955,
    longitude: 77.668,
    elevationM: 920,
    rmcDivision: 'RMC Chennai (MC Bengaluru)',
    wmoBlockNo: '43295',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Rotronic HC2A-S3',
      dataloggerModel: 'Sutron 9210 XL',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL VPN',
      batteryVoltage: '12.44 V (Float Nominal)',
      lastCalibDate: '15-Feb-2026',
      calibCertNo: 'CC-IMD-NABL-BLR-2026-0112',
    },
    baseline: { tempMean: 26.8, pressureMean: 1013.2, humidityMean: 62.0 },
  },
  {
    stationId: 'AWS-HYD-06',
    name: 'Begumpet Observatory, Hyderabad',
    hindiName: 'बेगमपेट वेधशाला, हैदराबाद',
    state: 'Telangana',
    latitude: 17.453,
    longitude: 78.467,
    elevationM: 531,
    rmcDivision: 'RMC Chennai (MC Hyderabad)',
    wmoBlockNo: '43128',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Setra 278 Barometer',
      humiditySensor: 'Vaisala Humicap 180R',
      dataloggerModel: 'Astra Micro AWS-200',
      telemetryUplink: 'INSAT-3D UHF DCP / Jio Private APN',
      batteryVoltage: '12.50 V (Float Nominal)',
      lastCalibDate: '11-Nov-2025',
      calibCertNo: 'CC-IMD-NABL-HYD-2025-0721',
    },
    baseline: { tempMean: 31.0, pressureMean: 1009.5, humidityMean: 56.0 },
  },
  {
    stationId: 'AWS-AHM-07',
    name: 'Sardar Vallabhbhai Patel Airport, Ahmedabad',
    hindiName: 'सरदार वल्लभभाई पटेल वेधशाला, अहमदाबाद',
    state: 'Gujarat',
    latitude: 23.072,
    longitude: 72.630,
    elevationM: 55,
    rmcDivision: 'RMC Mumbai (MC Ahmedabad)',
    wmoBlockNo: '42647',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A 4-Wire RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Vaisala Humicap 180R',
      dataloggerModel: 'Sutron 9210 XL',
      telemetryUplink: 'INSAT-3D UHF DCP / Vodafone-Idea Gov VPN',
      batteryVoltage: '12.39 V (Float Nominal)',
      lastCalibDate: '27-Oct-2025',
      calibCertNo: 'CC-IMD-NABL-AHM-2025-0688',
    },
    baseline: { tempMean: 33.8, pressureMean: 1007.8, humidityMean: 48.0 },
  },
  {
    stationId: 'AWS-JAI-09',
    name: 'Sanganer Observatory, Jaipur',
    hindiName: 'सांगानेर वेधशाला, जयपुर',
    state: 'Rajasthan',
    latitude: 26.824,
    longitude: 75.812,
    elevationM: 390,
    rmcDivision: 'RMC New Delhi (MC Jaipur)',
    wmoBlockNo: '42348',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Vaisala Humicap 180R',
      dataloggerModel: 'Campbell CR1000X',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL VPN',
      batteryVoltage: '12.46 V (Float Nominal)',
      lastCalibDate: '04-Dec-2025',
      calibCertNo: 'CC-IMD-NABL-JAI-2025-0955',
    },
    baseline: { tempMean: 35.2, pressureMean: 1006.8, humidityMean: 42.0 },
  },
  {
    stationId: 'AWS-LKO-10',
    name: 'Amausi Airport Meteorological Office, Lucknow',
    hindiName: 'अमौसी वेधशाला, लखनऊ',
    state: 'Uttar Pradesh',
    latitude: 26.760,
    longitude: 80.883,
    elevationM: 123,
    rmcDivision: 'RMC New Delhi (MC Lucknow)',
    wmoBlockNo: '42369',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Setra 278 Barometer',
      humiditySensor: 'Rotronic HC2A-S3',
      dataloggerModel: 'Sutron 9210 XL',
      telemetryUplink: 'INSAT-3D UHF DCP / Airtel Gov VPN',
      batteryVoltage: '12.52 V (Float Nominal)',
      lastCalibDate: '16-Nov-2025',
      calibCertNo: 'CC-IMD-NABL-LKO-2025-0812',
    },
    baseline: { tempMean: 32.5, pressureMean: 1009.6, humidityMean: 66.0 },
  },
  {
    stationId: 'AWS-BHP-11',
    name: 'Bairagarh Observatory, Bhopal',
    hindiName: 'बैरागढ़ वेधशाला, भोपाल',
    state: 'Madhya Pradesh',
    latitude: 23.287,
    longitude: 77.348,
    elevationM: 523,
    rmcDivision: 'RMC Nagpur (MC Bhopal)',
    wmoBlockNo: '42667',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Vaisala Humicap 180R',
      dataloggerModel: 'Astra Micro AWS-200',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL VPN',
      batteryVoltage: '12.41 V (Float Nominal)',
      lastCalibDate: '20-Oct-2025',
      calibCertNo: 'CC-IMD-NABL-BHP-2025-0649',
    },
    baseline: { tempMean: 30.0, pressureMean: 1010.2, humidityMean: 54.0 },
  },
  {
    stationId: 'AWS-PAT-12',
    name: 'Jay Prakash Narayan Airport, Patna',
    hindiName: 'जयप्रकाश नारायण वेधशाला, पटना',
    state: 'Bihar',
    latitude: 25.591,
    longitude: 85.088,
    elevationM: 52,
    rmcDivision: 'RMC Kolkata (MC Patna)',
    wmoBlockNo: '42492',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Rotronic HC2A-S3',
      dataloggerModel: 'Sutron 9210 XL',
      telemetryUplink: 'INSAT-3D UHF DCP / Airtel IoT',
      batteryVoltage: '12.48 V (Float Nominal)',
      lastCalibDate: '08-Jan-2026',
      calibCertNo: 'CC-IMD-NABL-PAT-2026-0015',
    },
    baseline: { tempMean: 31.6, pressureMean: 1010.8, humidityMean: 72.0 },
  },
  {
    stationId: 'AWS-GHY-13',
    name: 'Borjhar Meteorological Centre, Guwahati',
    hindiName: 'बोरझार मौसम केंद्र, गुवाहाटी',
    state: 'Assam',
    latitude: 26.106,
    longitude: 91.586,
    elevationM: 49,
    rmcDivision: 'RMC Guwahati',
    wmoBlockNo: '42410',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Setra 278 Barometer',
      humiditySensor: 'Vaisala Humicap 180R',
      dataloggerModel: 'Campbell CR1000X',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL Broadband',
      batteryVoltage: '12.56 V (Float Nominal)',
      lastCalibDate: '12-Dec-2025',
      calibCertNo: 'CC-IMD-NABL-GHY-2025-0994',
    },
    baseline: { tempMean: 28.0, pressureMean: 1012.2, humidityMean: 86.0 },
  },
  {
    stationId: 'AWS-SML-14',
    name: 'Shimla Ridge High-Altitude Observatory',
    hindiName: 'शिमला रिज वेधशाला, शिमला',
    state: 'Himachal Pradesh',
    latitude: 31.104,
    longitude: 77.173,
    elevationM: 2205,
    rmcDivision: 'RMC New Delhi (MC Shimla)',
    wmoBlockNo: '42083',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A Heated RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Vaisala Humicap Heated Sensor',
      dataloggerModel: 'Sutron 9210 XL',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL VPN',
      batteryVoltage: '12.68 V (Dual Solar System)',
      lastCalibDate: '25-Jan-2026',
      calibCertNo: 'CC-IMD-NABL-SML-2026-0062',
    },
    baseline: { tempMean: 21.0, pressureMean: 1014.2, humidityMean: 68.0 },
  },
  {
    stationId: 'AWS-TRV-15',
    name: 'Palayam Tropical Observatory, Thiruvananthapuram',
    hindiName: 'पालयम वेधशाला, तिरुवनंतपुरम',
    state: 'Kerala',
    latitude: 8.506,
    longitude: 76.956,
    elevationM: 15,
    rmcDivision: 'RMC Chennai (MC Thiruvananthapuram)',
    wmoBlockNo: '43371',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Rotronic HC2A-S3',
      dataloggerModel: 'Campbell CR1000X',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL VPN',
      batteryVoltage: '12.45 V (Float Nominal)',
      lastCalibDate: '18-Feb-2026',
      calibCertNo: 'CC-IMD-NABL-TRV-2026-0138',
    },
    baseline: { tempMean: 29.4, pressureMean: 1011.8, humidityMean: 84.0 },
  },
  {
    stationId: 'AWS-NAG-16',
    name: 'Sonegaon Meteorological Office, Nagpur',
    hindiName: 'सोनेगांव वेधशाला, नागपुर',
    state: 'Maharashtra',
    latitude: 21.100,
    longitude: 79.050,
    elevationM: 310,
    rmcDivision: 'RMC Nagpur',
    wmoBlockNo: '42867',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Vaisala Humicap 180R',
      dataloggerModel: 'Sutron 9210 XL',
      telemetryUplink: 'INSAT-3D UHF DCP / Airtel Gov APN',
      batteryVoltage: '12.40 V (Float Nominal)',
      lastCalibDate: '30-Nov-2025',
      calibCertNo: 'CC-IMD-NABL-NAG-2025-0877',
    },
    baseline: { tempMean: 32.2, pressureMean: 1009.0, humidityMean: 52.0 },
  },
  {
    stationId: 'AWS-SRN-17',
    name: 'Sheikh ul-Alam Meteorological Station, Srinagar',
    hindiName: 'शेख उल-आलम मौसम केंद्र, श्रीनगर',
    state: 'Jammu & Kashmir (UT)',
    latitude: 34.000,
    longitude: 74.770,
    elevationM: 1587,
    rmcDivision: 'RMC New Delhi (MC Srinagar)',
    wmoBlockNo: '42027',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A Heated RTD',
      pressureSensor: 'Setra 278 Barometer',
      humiditySensor: 'Rotronic HygroClip2-S3',
      dataloggerModel: 'Campbell CR1000X',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL Fiber Fallback',
      batteryVoltage: '12.72 V (Cold Climate Pack)',
      lastCalibDate: '10-Feb-2026',
      calibCertNo: 'CC-IMD-NABL-SRN-2026-0091',
    },
    baseline: { tempMean: 18.5, pressureMean: 1015.0, humidityMean: 65.0 },
  },
  {
    stationId: 'AWS-BBI-18',
    name: 'Biju Patnaik Coastal Plains Observatory, Bhubaneswar',
    hindiName: 'बीजू पटनायक वेधशाला, भुवनेश्वर',
    state: 'Odisha',
    latitude: 20.244,
    longitude: 85.818,
    elevationM: 42,
    rmcDivision: 'RMC Kolkata (MC Bhubaneswar)',
    wmoBlockNo: '42971',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Vaisala Humicap 180R',
      dataloggerModel: 'Astra Micro AWS-200',
      telemetryUplink: 'INSAT-3D UHF DCP / Jio VPN',
      batteryVoltage: '12.49 V (Float Nominal)',
      lastCalibDate: '05-Jan-2026',
      calibCertNo: 'CC-IMD-NABL-BBI-2026-0008',
    },
    baseline: { tempMean: 31.2, pressureMean: 1011.0, humidityMean: 76.0 },
  },
  {
    stationId: 'AWS-AGR-19',
    name: 'Kheria Civil Enclave Observatory, Agra',
    hindiName: 'खेरिया वेधशाला, आगरा',
    state: 'Uttar Pradesh',
    latitude: 27.156,
    longitude: 77.961,
    elevationM: 169,
    rmcDivision: 'RMC New Delhi',
    wmoBlockNo: '42266',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Rotronic HC2A-S3',
      dataloggerModel: 'Sutron 9210 XL',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL VPN',
      batteryVoltage: '12.43 V (Float Nominal)',
      lastCalibDate: '17-Oct-2025',
      calibCertNo: 'CC-IMD-NABL-AGR-2025-0611',
    },
    baseline: { tempMean: 33.4, pressureMean: 1008.8, humidityMean: 50.0 },
  },
  {
    stationId: 'AWS-VAP-20',
    name: 'Visakhapatnam Cyclone Warning Centre AWS',
    hindiName: 'चक्रवात चेतावनी केंद्र वेधशाला, विशाखापट्टनम',
    state: 'Andhra Pradesh',
    latitude: 17.720,
    longitude: 83.300,
    elevationM: 5,
    rmcDivision: 'RMC Chennai (MC Amaravati)',
    wmoBlockNo: '43149',
    sensorMetadata: {
      tempSensor: 'PT100 Class-A RTD',
      pressureSensor: 'Vaisala PTB110 Barometer',
      humiditySensor: 'Vaisala Humicap 180R',
      dataloggerModel: 'Campbell CR1000X',
      telemetryUplink: 'INSAT-3D UHF DCP / BSNL Leased Line',
      batteryVoltage: '12.54 V (Float Nominal)',
      lastCalibDate: '28-Nov-2025',
      calibCertNo: 'CC-IMD-NABL-VAP-2025-0862',
    },
    baseline: { tempMean: 30.2, pressureMean: 1012.0, humidityMean: 80.0 },
    status: 'SCHEDULED_CALIBRATION',
  },
];

export const getStationProfile = (id: string): IMDStationProfile => {
  return IMD_AWS_STATIONS.find((s) => s.stationId === id) || IMD_AWS_STATIONS[0];
};
